#!/usr/bin/env bash

#
# Setting CDPATH for systems w/multiple partitions or disks is handy
#
export CDPATH=:/Volumes/Mini-HD2/Users2/dgabbe/_git:/Volumes/Mini-HD2/Users2/dgabbe/R

export dggit=/Volumes/Mini-HD2/Users2/dgabbe/_git
