#!/usr/bin/env bash
#
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

#
# set PATH so it includes user's private bin if it exists
#
if [ -d "${HOME}/bin" ] ; then
    PATH="${HOME}/bin:$PATH"
fi

#
# Set machine specific environment variables and aliases if present. Useful for CDPATH
#
my_machine=${HOME}/.${HOSTNAME%.local}_${USER}_profile
if [ -e "${my_machine}" ]; then
  source ${my_machine}
fi

#
# opt out Homebrew analytics
#
export HOMEBREW_NO_ANALYTICS=1

#
# Required to make MacTex compatible w/older versions of Ruby.
# Deprecated in newer versions of Ruby and no longer a problem.
#
export LANGUAGE='en_US:en'
export LC_MESSAGES='en_US.UTF-8'
export LC_CTYPE='en_US.UTF-8'
export LC_COLLATE='en_US.UTF-8'

#
# Set options using set or shopt or export
#
set -o emacs
#
# bash-completion bug - https://github.com/scop/bash-completion/issues/44
#
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  set +o nounset
  source $(brew --prefix)/etc/bash_completion
else
  set -o nounset
fi
shopt -s checkwinsize # Update the values of LINES and COLUMNS after each command
export GIT_PS1_SHOWDIRTYSTATE=1
shopt -s histappend # Append to the history file, don't overwrite it
export HISTCONTROL='ignoredups:ignorespace' # don't put duplicate lines in the history.
export HISTSIZE=1000
export HISTFILESIZE=2000

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ${HOME}/.bash_aliases ]; then
    source ${HOME}/.bash_aliases
fi

if [ -f ${HOME}/.git_completion ]; then
    source ${HOME}/.git_completion
fi

#
# set a color prompt, git branch, & window title
# OS X reports 'xterm-256color'
#
case "$TERM" in
  xterm-*color | xterm | rxvt*)
    PS1='\[\e]0;\u@\h: \w\a\]$SHLVL: \[\033[00;34m\]\u\[\033[00m\]@\[\033[00;34m\]\h\[\033[00m\]: \[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 "(%s)")\$\n\r'
    PS2='\[\033[00;34m\]> '
    ;;
  *)
    PS1='\[\e]0;\u@\h: \w\a\]$SHLVL:\! \u@\h:\w$(__git_ps1 "(%s)")\$\n\r'
    ;;
esac

#
# load rvm
#
if [ -s "${HOME}/.rvm/scripts/rvm" ]; then
  PATH=$PATH:${HOME}/.rvm/bin # Add RVM to PATH for scripting
  source "${HOME}/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
  # load git prompt
  if [[ $- == *i* ]]
  then
    . ${HOME}/.rvm/contrib/ps1_functions
    ps1_set --prompt \$
  fi
fi

#
# Stuff from Bosco's file, but not supported on OS X
#
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
